package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1



/**
 * ChitietdondatId generated by hbm2java
 */
public class ChitietdondatId  implements java.io.Serializable {


     private int maMh;
     private int maDon;

    public ChitietdondatId() {
    }

    public ChitietdondatId(int maMh, int maDon) {
       this.maMh = maMh;
       this.maDon = maDon;
    }
   
    public int getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(int maMh) {
        this.maMh = maMh;
    }
    public int getMaDon() {
        return this.maDon;
    }
    
    public void setMaDon(int maDon) {
        this.maDon = maDon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChitietdondatId) ) return false;
		 ChitietdondatId castOther = ( ChitietdondatId ) other; 
         
		 return (this.getMaMh()==castOther.getMaMh())
 && (this.getMaDon()==castOther.getMaDon());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMaMh();
         result = 37 * result + this.getMaDon();
         return result;
   }   


}


