package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1



/**
 * ChitietdonnhaphangId generated by hbm2java
 */
public class ChitietdonnhaphangId  implements java.io.Serializable {


     private int maMh;
     private int maDonNhap;

    public ChitietdonnhaphangId() {
    }

    public ChitietdonnhaphangId(int maMh, int maDonNhap) {
       this.maMh = maMh;
       this.maDonNhap = maDonNhap;
    }
   
    public int getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(int maMh) {
        this.maMh = maMh;
    }
    public int getMaDonNhap() {
        return this.maDonNhap;
    }
    
    public void setMaDonNhap(int maDonNhap) {
        this.maDonNhap = maDonNhap;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChitietdonnhaphangId) ) return false;
		 ChitietdonnhaphangId castOther = ( ChitietdonnhaphangId ) other; 
         
		 return (this.getMaMh()==castOther.getMaMh())
 && (this.getMaDonNhap()==castOther.getMaDonNhap());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMaMh();
         result = 37 * result + this.getMaDonNhap();
         return result;
   }   


}


