package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1



/**
 * Chitietdonnhaphang generated by hbm2java
 */
public class Chitietdonnhaphang  implements java.io.Serializable {


     private ChitietdonnhaphangId id;
     private Donnhaphang donnhaphang;
     private Mathang mathang;
     private int soLuongNhap;

    public Chitietdonnhaphang() {
    }

    public Chitietdonnhaphang(ChitietdonnhaphangId id, Donnhaphang donnhaphang, Mathang mathang, int soLuongNhap) {
       this.id = id;
       this.donnhaphang = donnhaphang;
       this.mathang = mathang;
       this.soLuongNhap = soLuongNhap;
    }
   
    public ChitietdonnhaphangId getId() {
        return this.id;
    }
    
    public void setId(ChitietdonnhaphangId id) {
        this.id = id;
    }
    public Donnhaphang getDonnhaphang() {
        return this.donnhaphang;
    }
    
    public void setDonnhaphang(Donnhaphang donnhaphang) {
        this.donnhaphang = donnhaphang;
    }
    public Mathang getMathang() {
        return this.mathang;
    }
    
    public void setMathang(Mathang mathang) {
        this.mathang = mathang;
    }
    public int getSoLuongNhap() {
        return this.soLuongNhap;
    }
    
    public void setSoLuongNhap(int soLuongNhap) {
        this.soLuongNhap = soLuongNhap;
    }




}


