package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1



/**
 * Chitietdontra generated by hbm2java
 */
public class Chitietdontra  implements java.io.Serializable {


     private ChitietdontraId id;
     private Dontrahang dontrahang;
     private Mathang mathang;
     private int soLuongTra;

    public Chitietdontra() {
    }

    public Chitietdontra(ChitietdontraId id, Dontrahang dontrahang, Mathang mathang, int soLuongTra) {
       this.id = id;
       this.dontrahang = dontrahang;
       this.mathang = mathang;
       this.soLuongTra = soLuongTra;
    }
   
    public ChitietdontraId getId() {
        return this.id;
    }
    
    public void setId(ChitietdontraId id) {
        this.id = id;
    }
    public Dontrahang getDontrahang() {
        return this.dontrahang;
    }
    
    public void setDontrahang(Dontrahang dontrahang) {
        this.dontrahang = dontrahang;
    }
    public Mathang getMathang() {
        return this.mathang;
    }
    
    public void setMathang(Mathang mathang) {
        this.mathang = mathang;
    }
    public int getSoLuongTra() {
        return this.soLuongTra;
    }
    
    public void setSoLuongTra(int soLuongTra) {
        this.soLuongTra = soLuongTra;
    }




}


