package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1



/**
 * Chitietdondat generated by hbm2java
 */
public class Chitietdondat  implements java.io.Serializable {


     private ChitietdondatId id;
     private Dondathang dondathang;
     private Mathang mathang;
     private int soLuong;
     private String giaBan;
     private String tinhTrang;

    public Chitietdondat() {
    }

    public Chitietdondat(ChitietdondatId id, Dondathang dondathang, Mathang mathang, int soLuong, String giaBan, String tinhTrang) {
       this.id = id;
       this.dondathang = dondathang;
       this.mathang = mathang;
       this.soLuong = soLuong;
       this.giaBan = giaBan;
       this.tinhTrang = tinhTrang;
    }
   
    public ChitietdondatId getId() {
        return this.id;
    }
    
    public void setId(ChitietdondatId id) {
        this.id = id;
    }
    public Dondathang getDondathang() {
        return this.dondathang;
    }
    
    public void setDondathang(Dondathang dondathang) {
        this.dondathang = dondathang;
    }
    public Mathang getMathang() {
        return this.mathang;
    }
    
    public void setMathang(Mathang mathang) {
        this.mathang = mathang;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public String getGiaBan() {
        return this.giaBan;
    }
    
    public void setGiaBan(String giaBan) {
        this.giaBan = giaBan;
    }
    public String getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(String tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


