package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doitacquangcao generated by hbm2java
 */
public class Doitacquangcao  implements java.io.Serializable {


     private int maDt;
     private String ten;
     private Set hopdongquangcaos = new HashSet(0);

    public Doitacquangcao() {
    }

	
    public Doitacquangcao(int maDt, String ten) {
        this.maDt = maDt;
        this.ten = ten;
    }
    public Doitacquangcao(int maDt, String ten, Set hopdongquangcaos) {
       this.maDt = maDt;
       this.ten = ten;
       this.hopdongquangcaos = hopdongquangcaos;
    }
   
    public int getMaDt() {
        return this.maDt;
    }
    
    public void setMaDt(int maDt) {
        this.maDt = maDt;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getHopdongquangcaos() {
        return this.hopdongquangcaos;
    }
    
    public void setHopdongquangcaos(Set hopdongquangcaos) {
        this.hopdongquangcaos = hopdongquangcaos;
    }




}


