package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1


import Database.DonDatHangDB;
import java.util.HashSet;
import java.util.Set;

/**
 * Dondathang generated by hbm2java
 */
public class Dondathang  implements java.io.Serializable {


     private int maDon;
     private Khachhang khachhang;
     private Nhanvien nhanvien;
     private boolean xacNhan;
     private String hinhThucThanhToan;
     private String tongTien;
     private Set chitietdondats = new HashSet(0);

    public Dondathang() {
    }

	
    public Dondathang(int maDon, Khachhang khachhang, Nhanvien nhanvien, boolean xacNhan, String hinhThucThanhToan, String tongTien) {
        this.maDon = maDon;
        this.khachhang = khachhang;
        this.nhanvien = nhanvien;
        this.xacNhan = xacNhan;
        this.hinhThucThanhToan = hinhThucThanhToan;
        this.tongTien = tongTien;
    }
    public Dondathang(int maDon, Khachhang khachhang, Nhanvien nhanvien, boolean xacNhan, String hinhThucThanhToan, String tongTien, Set chitietdondats) {
       this.maDon = maDon;
       this.khachhang = khachhang;
       this.nhanvien = nhanvien;
       this.xacNhan = xacNhan;
       this.hinhThucThanhToan = hinhThucThanhToan;
       this.tongTien = tongTien;
       this.chitietdondats = chitietdondats;
    }
   
    public int getMaDon() {
        return this.maDon;
    }
    
    public void setMaDon(int maDon) {
        this.maDon = maDon;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public boolean isXacNhan() {
        return this.xacNhan;
    }
    
    public void setXacNhan(boolean xacNhan) {
        this.xacNhan = xacNhan;
    }
    public String getHinhThucThanhToan() {
        return this.hinhThucThanhToan;
    }
    
    public void setHinhThucThanhToan(String hinhThucThanhToan) {
        this.hinhThucThanhToan = hinhThucThanhToan;
    }
    public String getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(String tongTien) {
        this.tongTien = tongTien;
    }
    public Set getChitietdondats() {
        return this.chitietdondats;
    }
    
    public void setChitietdondats(Set chitietdondats) {
        this.chitietdondats = chitietdondats;
    }

    public static boolean KiemTraTonTai(int ma){
        return(!DonDatHangDB.Doc("From Dondathang where MaKH = " + ma).isEmpty());
    }


}


