package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donnhaphang generated by hbm2java
 */
public class Donnhaphang  implements java.io.Serializable {


     private int maDonNhap;
     private Nhacungcap nhacungcap;
     private Nhanvien nhanvien;
     private Date ngayLap;
     private String lyDo;
     private Set chitietdonnhaphangs = new HashSet(0);

    public Donnhaphang() {
    }

	
    public Donnhaphang(int maDonNhap, Nhacungcap nhacungcap, Nhanvien nhanvien, Date ngayLap, String lyDo) {
        this.maDonNhap = maDonNhap;
        this.nhacungcap = nhacungcap;
        this.nhanvien = nhanvien;
        this.ngayLap = ngayLap;
        this.lyDo = lyDo;
    }
    public Donnhaphang(int maDonNhap, Nhacungcap nhacungcap, Nhanvien nhanvien, Date ngayLap, String lyDo, Set chitietdonnhaphangs) {
       this.maDonNhap = maDonNhap;
       this.nhacungcap = nhacungcap;
       this.nhanvien = nhanvien;
       this.ngayLap = ngayLap;
       this.lyDo = lyDo;
       this.chitietdonnhaphangs = chitietdonnhaphangs;
    }
   
    public int getMaDonNhap() {
        return this.maDonNhap;
    }
    
    public void setMaDonNhap(int maDonNhap) {
        this.maDonNhap = maDonNhap;
    }
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Date getNgayLap() {
        return this.ngayLap;
    }
    
    public void setNgayLap(Date ngayLap) {
        this.ngayLap = ngayLap;
    }
    public String getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(String lyDo) {
        this.lyDo = lyDo;
    }
    public Set getChitietdonnhaphangs() {
        return this.chitietdonnhaphangs;
    }
    
    public void setChitietdonnhaphangs(Set chitietdonnhaphangs) {
        this.chitietdonnhaphangs = chitietdonnhaphangs;
    }




}


