package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1



/**
 * GopyId generated by hbm2java
 */
public class GopyId  implements java.io.Serializable {


     private int maSp;
     private int maKh;

    public GopyId() {
    }

    public GopyId(int maSp, int maKh) {
       this.maSp = maSp;
       this.maKh = maKh;
    }
   
    public int getMaSp() {
        return this.maSp;
    }
    
    public void setMaSp(int maSp) {
        this.maSp = maSp;
    }
    public int getMaKh() {
        return this.maKh;
    }
    
    public void setMaKh(int maKh) {
        this.maKh = maKh;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GopyId) ) return false;
		 GopyId castOther = ( GopyId ) other; 
         
		 return (this.getMaSp()==castOther.getMaSp())
 && (this.getMaKh()==castOther.getMaKh());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMaSp();
         result = 37 * result + this.getMaKh();
         return result;
   }   


}


