package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1



/**
 * Gopy generated by hbm2java
 */
public class Gopy  implements java.io.Serializable {


     private GopyId id;
     private Khachhang khachhang;
     private Mathang mathang;
     private String cmt;

    public Gopy() {
    }

    public Gopy(GopyId id, Khachhang khachhang, Mathang mathang, String cmt) {
       this.id = id;
       this.khachhang = khachhang;
       this.mathang = mathang;
       this.cmt = cmt;
    }
   
    public GopyId getId() {
        return this.id;
    }
    
    public void setId(GopyId id) {
        this.id = id;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Mathang getMathang() {
        return this.mathang;
    }
    
    public void setMathang(Mathang mathang) {
        this.mathang = mathang;
    }
    public String getCmt() {
        return this.cmt;
    }
    
    public void setCmt(String cmt) {
        this.cmt = cmt;
    }




}


