package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hopdongquangcao generated by hbm2java
 */
public class Hopdongquangcao  implements java.io.Serializable {


     private int maHd;
     private Doitacquangcao doitacquangcao;
     private Nhanvien nhanvien;
     private Date ngayKi;
     private int thoiHan;
     private String thongTin;

    public Hopdongquangcao() {
    }

    public Hopdongquangcao(int maHd, Doitacquangcao doitacquangcao, Nhanvien nhanvien, Date ngayKi, int thoiHan, String thongTin) {
       this.maHd = maHd;
       this.doitacquangcao = doitacquangcao;
       this.nhanvien = nhanvien;
       this.ngayKi = ngayKi;
       this.thoiHan = thoiHan;
       this.thongTin = thongTin;
    }
   
    public int getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(int maHd) {
        this.maHd = maHd;
    }
    public Doitacquangcao getDoitacquangcao() {
        return this.doitacquangcao;
    }
    
    public void setDoitacquangcao(Doitacquangcao doitacquangcao) {
        this.doitacquangcao = doitacquangcao;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Date getNgayKi() {
        return this.ngayKi;
    }
    
    public void setNgayKi(Date ngayKi) {
        this.ngayKi = ngayKi;
    }
    public int getThoiHan() {
        return this.thoiHan;
    }
    
    public void setThoiHan(int thoiHan) {
        this.thoiHan = thoiHan;
    }
    public String getThongTin() {
        return this.thongTin;
    }
    
    public void setThongTin(String thongTin) {
        this.thongTin = thongTin;
    }




}


