package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loainhanvien generated by hbm2java
 */
public class Loainhanvien  implements java.io.Serializable {


     private int maLoaiNv;
     private String tenLoai;
     private Set nhanviens = new HashSet(0);

    public Loainhanvien() {
    }

	
    public Loainhanvien(int maLoaiNv, String tenLoai) {
        this.maLoaiNv = maLoaiNv;
        this.tenLoai = tenLoai;
    }
    public Loainhanvien(int maLoaiNv, String tenLoai, Set nhanviens) {
       this.maLoaiNv = maLoaiNv;
       this.tenLoai = tenLoai;
       this.nhanviens = nhanviens;
    }
   
    public int getMaLoaiNv() {
        return this.maLoaiNv;
    }
    
    public void setMaLoaiNv(int maLoaiNv) {
        this.maLoaiNv = maLoaiNv;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


