package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loaihang generated by hbm2java
 */
public class Loaihang  implements java.io.Serializable {


     private int maLoai;
     private String ten;
     private Set mathangs = new HashSet(0);

    public Loaihang() {
    }

	
    public Loaihang(int maLoai, String ten) {
        this.maLoai = maLoai;
        this.ten = ten;
    }
    public Loaihang(int maLoai, String ten, Set mathangs) {
       this.maLoai = maLoai;
       this.ten = ten;
       this.mathangs = mathangs;
    }
   
    public int getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(int maLoai) {
        this.maLoai = maLoai;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getMathangs() {
        return this.mathangs;
    }
    
    public void setMathangs(Set mathangs) {
        this.mathangs = mathangs;
    }




}


