package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1


import Database.DAO;
import Database.MatHangDB;
import Entity.Loaihang;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Mathang generated by hbm2java
 */
public class Mathang  implements java.io.Serializable {


     private int maMatHang;
     private Loaihang loaihang;
     private String ten;
     private int gia;
     private int soLuong;
     private Set chitietdondats = new HashSet(0);
     private Set chitietdonnhaphangs = new HashSet(0);
     private Set gopies = new HashSet(0);
     private Set chitietdontras = new HashSet(0);

    public Mathang() {
    }

    public Mathang(int maloaihang, String ten, int gia, int soLuong) {
        this.loaihang = Loaihang.LayLoaiHang(maloaihang);
        this.ten = ten;
        this.gia = gia;
        this.soLuong = soLuong;
    }
    public Mathang(int maMatHang, Loaihang loaihang, String ten, int gia, int soLuong) {
        this.maMatHang = maMatHang;
        this.loaihang = loaihang;
        this.ten = ten;
        this.gia = gia;
        this.soLuong = soLuong;
    }
    public Mathang(int maMatHang, Loaihang loaihang, String ten, int gia, int soLuong, Set chitietdondats, Set chitietdonnhaphangs, Set gopies, Set chitietdontras) {
       this.maMatHang = maMatHang;
       this.loaihang = loaihang;
       this.ten = ten;
       this.gia = gia;
       this.soLuong = soLuong;
       this.chitietdondats = chitietdondats;
       this.chitietdonnhaphangs = chitietdonnhaphangs;
       this.gopies = gopies;
       this.chitietdontras = chitietdontras;
    }
   
    public int getMaMatHang() {
        return this.maMatHang;
    }
    
    public void setMaMatHang(int maMatHang) {
        this.maMatHang = maMatHang;
    }
    public Loaihang getLoaihang() {
        return this.loaihang;
    }
    
    public void setLoaihang(Loaihang loaihang) {
        this.loaihang = loaihang;
    }
    
    public void setLoaihang(int maloaihang) {
        this.loaihang = Loaihang.LayLoaiHang(maloaihang);
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public int getGia() {
        return this.gia;
    }
    
    public void setGia(int gia) {
        this.gia = gia;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public Set getChitietdondats() {
        return this.chitietdondats;
    }
    
    public void setChitietdondats(Set chitietdondats) {
        this.chitietdondats = chitietdondats;
    }
    public Set getChitietdonnhaphangs() {
        return this.chitietdonnhaphangs;
    }
    
    public void setChitietdonnhaphangs(Set chitietdonnhaphangs) {
        this.chitietdonnhaphangs = chitietdonnhaphangs;
    }
    public Set getGopies() {
        return this.gopies;
    }
    
    public void setGopies(Set gopies) {
        this.gopies = gopies;
    }
    public Set getChitietdontras() {
        return this.chitietdontras;
    }
    
    public void setChitietdontras(Set chitietdontras) {
        this.chitietdontras = chitietdontras;
    }


    public static List<Mathang> DanhSach(String ten, String ma){
        String query = "From Mathang where 1 = 1";
        if(!ma.isEmpty()){
            query += " and maMatHang = " + ma;
        }
        if(!ten.isEmpty()){
            query += " and ten like '%" + ten + "%'";
        }
        return MatHangDB.Doc(query);
    }

    
    public static boolean ThemMatHang(Mathang h){
        if(!KiemTraTonTai(h)){
            MatHangDB.Them(h);
            return true;
        }
        return false;
    }
    
    public static boolean KiemTraTonTai(Mathang h){
        return (!MatHangDB.Doc("From Mathang where ten = '" + h.getTen() + "'").isEmpty());
    }
    
    public static boolean KiemTraTonTaiUpdate(Mathang h){
        return (!MatHangDB.Doc("From Mathang where (ten = '" + h.getTen() + "') and maMatHang != " + h.getMaMatHang()).isEmpty());
    }
    
    public static boolean UpdateMatHang(Mathang h){
        if(!KiemTraTonTaiUpdate(h)){
            MatHangDB.Update(h);
            return true;
        }
        return false;
    }
    
    public static boolean XoaMatHang(Mathang h){
        if(!Dondathang.KiemTraTonTai(h.maMatHang)){
            MatHangDB.Delete(h);
            return true;
        }
        return false;
    }
    public static Mathang LayMatHang(int ma){
        String query = "From Mathang where 1 = 1";
        query += " and maMathang = " + ma ;
        return MatHangDB.Doc(query).get(0);
    }
     public static boolean UpdateSL(Mathang h){
         return MatHangDB.UpdateSL(h);
    }
}


