package Entity;
// Generated Aug 3, 2020 8:58:34 PM by Hibernate Tools 4.3.1


import Database.NhanVienDB;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private int maNhanVien;
     private Loainhanvien loainhanvien;
     private String ten;
     private String pass;
     private Set dontrahangs = new HashSet(0);
     private Set hopdongquangcaos = new HashSet(0);
     private Set dondathangs = new HashSet(0);
     private Set donnhaphangs = new HashSet(0);

    public Nhanvien() {
    }

	
    public Nhanvien(int maNhanVien, Loainhanvien loainhanvien, String ten, String pass) {
        this.maNhanVien = maNhanVien;
        this.loainhanvien = loainhanvien;
        this.ten = ten;
        this.pass = pass;
    }
    public Nhanvien(int maNhanVien, Loainhanvien loainhanvien, String ten, String pass, Set dontrahangs, Set hopdongquangcaos, Set dondathangs, Set donnhaphangs) {
       this.maNhanVien = maNhanVien;
       this.loainhanvien = loainhanvien;
       this.ten = ten;
       this.dontrahangs = dontrahangs;
       this.hopdongquangcaos = hopdongquangcaos;
       this.dondathangs = dondathangs;
       this.donnhaphangs = donnhaphangs;
       this.pass = pass;
    }
   
    public int getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(int maNhanVien) {
        this.maNhanVien = maNhanVien;
    }
    public Loainhanvien getLoainhanvien() {
        return this.loainhanvien;
    }
    
    public void setLoainhanvien(Loainhanvien loainhanvien) {
        this.loainhanvien = loainhanvien;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getDontrahangs() {
        return this.dontrahangs;
    }
    
    public void setDontrahangs(Set dontrahangs) {
        this.dontrahangs = dontrahangs;
    }
    public Set getHopdongquangcaos() {
        return this.hopdongquangcaos;
    }
    
    public void setHopdongquangcaos(Set hopdongquangcaos) {
        this.hopdongquangcaos = hopdongquangcaos;
    }
    public Set getDondathangs() {
        return this.dondathangs;
    }
    
    public void setDondathangs(Set dondathangs) {
        this.dondathangs = dondathangs;
    }
    public Set getDonnhaphangs() {
        return this.donnhaphangs;
    }
    
    public void setDonnhaphangs(Set donnhaphangs) {
        this.donnhaphangs = donnhaphangs;
    }

    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    
    public static boolean CheckPass(String username, String pass){
        return (!NhanVienDB.Doc(Integer.valueOf(username), pass).isEmpty());
    }

}


